/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.ArrayList;
import java.util.HashSet;

public class Admin_GUI extends javax.swing.JFrame {
    private CardLayout T_cardstack;
    private CardLayout inner_cardstack;
    /**
     * Creates new form Admin_GUI
     */
    public Admin_GUI() {
        initComponents();
        setVisible(true);
        T_cardstack = (CardLayout) this.Top_cardstack.getLayout();
        inner_cardstack = (CardLayout) this.internal_cardstack.getLayout();
        
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top_cardstack = new javax.swing.JPanel();
        Login_page = new javax.swing.JPanel();
        Sigin_panel = new javax.swing.JPanel();
        Welcome_label = new javax.swing.JLabel();
        Username_field = new javax.swing.JTextField();
        Password_field = new javax.swing.JTextField();
        Username_label = new javax.swing.JLabel();
        Password_label = new javax.swing.JLabel();
        Signin_label = new javax.swing.JLabel();
        Image_panel = new javax.swing.JPanel();
        image_label = new javax.swing.JLabel();
        Landing_page = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        Home_Highlight = new javax.swing.JPanel();
        Home_label = new javax.swing.JLabel();
        Manage_flight_highlight = new javax.swing.JPanel();
        Manage_flight_label = new javax.swing.JLabel();
        Add_flight_label = new javax.swing.JLabel();
        Add_flight_highlight = new javax.swing.JPanel();
        NoFlyList_label = new javax.swing.JLabel();
        NoFlyList_highlight = new javax.swing.JPanel();
        internal_cardstack = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        card_home = new javax.swing.JPanel();
        lbl_AdminProfile = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelhomelite = new javax.swing.JLabel();
        home1 = new javax.swing.JPanel();
        jLabelCompanyinfo = new javax.swing.JLabel();
        home2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelfirstname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabellastname = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabeladdress = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelsalary = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabeldesignation = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Manage_flights = new javax.swing.JPanel();
        card_home1 = new javax.swing.JPanel();
        lbl_AdminProfile1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelhomelite1 = new javax.swing.JLabel();
        home3 = new javax.swing.JPanel();
        jLabelCompanyinfo1 = new javax.swing.JLabel();
        home4 = new javax.swing.JPanel();
        Add_flight = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        View_NoFlyList = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Top_cardstack.setLayout(new java.awt.CardLayout());

        Sigin_panel.setBackground(new java.awt.Color(247, 127, 0));

        Welcome_label.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        Welcome_label.setForeground(new java.awt.Color(255, 255, 255));
        Welcome_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome_label.setText("Welcome to XYZ Airlines");

        Username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_fieldActionPerformed(evt);
            }
        });

        Password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_fieldActionPerformed(evt);
            }
        });

        Username_label.setForeground(new java.awt.Color(255, 255, 255));
        Username_label.setText("Username");

        Password_label.setForeground(new java.awt.Color(255, 255, 255));
        Password_label.setText("Password");

        Signin_label.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        Signin_label.setForeground(new java.awt.Color(255, 255, 255));
        Signin_label.setText("Sign in");
        Signin_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Signin_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Sigin_panelLayout = new javax.swing.GroupLayout(Sigin_panel);
        Sigin_panel.setLayout(Sigin_panelLayout);
        Sigin_panelLayout.setHorizontalGroup(
            Sigin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sigin_panelLayout.createSequentialGroup()
                .addGroup(Sigin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sigin_panelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(Sigin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Sigin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Welcome_label, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(Username_field)
                                .addComponent(Password_field))
                            .addComponent(Username_label)
                            .addComponent(Password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Sigin_panelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(Signin_label)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        Sigin_panelLayout.setVerticalGroup(
            Sigin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sigin_panelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Welcome_label)
                .addGap(81, 81, 81)
                .addComponent(Username_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(Password_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(Signin_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Image_panel.setBackground(new java.awt.Color(255, 255, 255));

        image_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/Plane_image.jpg"))); // NOI18N

        javax.swing.GroupLayout Image_panelLayout = new javax.swing.GroupLayout(Image_panel);
        Image_panel.setLayout(Image_panelLayout);
        Image_panelLayout.setHorizontalGroup(
            Image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Image_panelLayout.setVerticalGroup(
            Image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image_label, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Login_pageLayout = new javax.swing.GroupLayout(Login_page);
        Login_page.setLayout(Login_pageLayout);
        Login_pageLayout.setHorizontalGroup(
            Login_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_pageLayout.createSequentialGroup()
                .addComponent(Sigin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Image_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        Login_pageLayout.setVerticalGroup(
            Login_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sigin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Image_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Top_cardstack.add(Login_page, "Login_card");
        Login_page.getAccessibleContext().setAccessibleName("Login_page");

        Landing_page.setPreferredSize(new java.awt.Dimension(612, 408));

        Navbar.setBackground(new java.awt.Color(240, 40, 40));

        Home_Highlight.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout Home_HighlightLayout = new javax.swing.GroupLayout(Home_Highlight);
        Home_Highlight.setLayout(Home_HighlightLayout);
        Home_HighlightLayout.setHorizontalGroup(
            Home_HighlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        Home_HighlightLayout.setVerticalGroup(
            Home_HighlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        Home_label.setBackground(new java.awt.Color(247, 127, 0));
        Home_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Home_label.setForeground(new java.awt.Color(255, 255, 255));
        Home_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home_label.setText("Home");
        Home_label.setOpaque(true);
        Home_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_labelMouseClicked(evt);
            }
        });

        Manage_flight_highlight.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout Manage_flight_highlightLayout = new javax.swing.GroupLayout(Manage_flight_highlight);
        Manage_flight_highlight.setLayout(Manage_flight_highlightLayout);
        Manage_flight_highlightLayout.setHorizontalGroup(
            Manage_flight_highlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        Manage_flight_highlightLayout.setVerticalGroup(
            Manage_flight_highlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        Manage_flight_label.setBackground(new java.awt.Color(247, 127, 0));
        Manage_flight_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Manage_flight_label.setForeground(new java.awt.Color(255, 255, 255));
        Manage_flight_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Manage_flight_label.setText("Manage Flights");
        Manage_flight_label.setOpaque(true);
        Manage_flight_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Manage_flight_labelMouseClicked(evt);
            }
        });

        Add_flight_label.setBackground(new java.awt.Color(247, 127, 0));
        Add_flight_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Add_flight_label.setForeground(new java.awt.Color(255, 255, 255));
        Add_flight_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add_flight_label.setText("Add Flight");
        Add_flight_label.setOpaque(true);
        Add_flight_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_flight_labelMouseClicked(evt);
            }
        });

        Add_flight_highlight.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout Add_flight_highlightLayout = new javax.swing.GroupLayout(Add_flight_highlight);
        Add_flight_highlight.setLayout(Add_flight_highlightLayout);
        Add_flight_highlightLayout.setHorizontalGroup(
            Add_flight_highlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        Add_flight_highlightLayout.setVerticalGroup(
            Add_flight_highlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        NoFlyList_label.setBackground(new java.awt.Color(247, 127, 0));
        NoFlyList_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoFlyList_label.setForeground(new java.awt.Color(255, 255, 255));
        NoFlyList_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoFlyList_label.setText("Manage No-fly list");
        NoFlyList_label.setOpaque(true);
        NoFlyList_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoFlyList_labelMouseClicked(evt);
            }
        });

        NoFlyList_highlight.setBackground(new java.awt.Color(250, 250, 250));

        javax.swing.GroupLayout NoFlyList_highlightLayout = new javax.swing.GroupLayout(NoFlyList_highlight);
        NoFlyList_highlight.setLayout(NoFlyList_highlightLayout);
        NoFlyList_highlightLayout.setHorizontalGroup(
            NoFlyList_highlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        NoFlyList_highlightLayout.setVerticalGroup(
            NoFlyList_highlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Manage_flight_highlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_flight_highlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoFlyList_highlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home_Highlight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_flight_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Manage_flight_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoFlyList_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home_label, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Home_Highlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home_label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Manage_flight_highlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Manage_flight_label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Add_flight_highlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_flight_label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NoFlyList_highlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoFlyList_label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Home_Highlight.getAccessibleContext().setAccessibleName("Home_Highlight");

        internal_cardstack.setLayout(new java.awt.CardLayout());

        card_home.setBackground(new java.awt.Color(255, 102, 102));
        card_home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_AdminProfile.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lbl_AdminProfile.setForeground(new java.awt.Color(51, 0, 51));
        lbl_AdminProfile.setText(" Admin Profile ");
        lbl_AdminProfile.setMaximumSize(new java.awt.Dimension(150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("|");

        jLabelhomelite.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelhomelite.setForeground(new java.awt.Color(102, 102, 102));
        jLabelhomelite.setText("Home");

        home1.setBackground(new java.awt.Color(255, 204, 102));

        jLabelCompanyinfo.setBackground(new java.awt.Color(0, 102, 102));
        jLabelCompanyinfo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabelCompanyinfo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCompanyinfo.setText("Company Information");

        home2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setText("CNIC:");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("XYZ");

        jLabelfirstname.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabelfirstname.setText("First Name:");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("XYZ");

        jLabellastname.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabellastname.setText("Last Name: ");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("1234567891011");

        jLabeladdress.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabeladdress.setText("Address:");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("1 XYZ street,XYZ city,Pakistan");

        jLabelsalary.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabelsalary.setText("Salary:");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Rs.500,000");

        jLabeldesignation.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabeldesignation.setText("Designation:");

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("XYZ");

        javax.swing.GroupLayout home2Layout = new javax.swing.GroupLayout(home2);
        home2.setLayout(home2Layout);
        home2Layout.setHorizontalGroup(
            home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabellastname, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeldesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(home2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabelsalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(home2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(home2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabeladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(470, Short.MAX_VALUE))
        );
        home2Layout.setVerticalGroup(
            home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelfirstname)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabeladdress)
                    .addComponent(jLabel8)
                    .addComponent(jLabellastname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabeldesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout home1Layout = new javax.swing.GroupLayout(home1);
        home1.setLayout(home1Layout);
        home1Layout.setHorizontalGroup(
            home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home1Layout.createSequentialGroup()
                .addGroup(home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCompanyinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        home1Layout.setVerticalGroup(
            home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCompanyinfo)
                .addGap(18, 18, 18)
                .addComponent(home2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout card_homeLayout = new javax.swing.GroupLayout(card_home);
        card_home.setLayout(card_homeLayout);
        card_homeLayout.setHorizontalGroup(
            card_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_AdminProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelhomelite, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(card_homeLayout.createSequentialGroup()
                .addComponent(home1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card_homeLayout.setVerticalGroup(
            card_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_homeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(card_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_AdminProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelhomelite))
                .addGap(18, 18, 18)
                .addComponent(home1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(631, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(card_home, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(card_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        internal_cardstack.add(Home, "Home");

        card_home1.setBackground(new java.awt.Color(255, 102, 102));
        card_home1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_AdminProfile1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lbl_AdminProfile1.setForeground(new java.awt.Color(51, 0, 51));
        lbl_AdminProfile1.setText(" Admin Profile ");
        lbl_AdminProfile1.setMaximumSize(new java.awt.Dimension(150, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("|");

        jLabelhomelite1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabelhomelite1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelhomelite1.setText("Manage Flights");

        home3.setBackground(new java.awt.Color(255, 204, 102));

        jLabelCompanyinfo1.setBackground(new java.awt.Color(0, 102, 102));
        jLabelCompanyinfo1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabelCompanyinfo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCompanyinfo1.setText("Flight Information Information");

        home4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout home4Layout = new javax.swing.GroupLayout(home4);
        home4.setLayout(home4Layout);
        home4Layout.setHorizontalGroup(
            home4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1154, Short.MAX_VALUE)
        );
        home4Layout.setVerticalGroup(
            home4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout home3Layout = new javax.swing.GroupLayout(home3);
        home3.setLayout(home3Layout);
        home3Layout.setHorizontalGroup(
            home3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home3Layout.createSequentialGroup()
                .addGroup(home3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCompanyinfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        home3Layout.setVerticalGroup(
            home3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCompanyinfo1)
                .addGap(18, 18, 18)
                .addComponent(home4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout card_home1Layout = new javax.swing.GroupLayout(card_home1);
        card_home1.setLayout(card_home1Layout);
        card_home1Layout.setHorizontalGroup(
            card_home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_home1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_AdminProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelhomelite1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(card_home1Layout.createSequentialGroup()
                .addComponent(home3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card_home1Layout.setVerticalGroup(
            card_home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_home1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(card_home1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_AdminProfile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelhomelite1))
                .addGap(18, 18, 18)
                .addComponent(home3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(631, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Manage_flightsLayout = new javax.swing.GroupLayout(Manage_flights);
        Manage_flights.setLayout(Manage_flightsLayout);
        Manage_flightsLayout.setHorizontalGroup(
            Manage_flightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_flightsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(card_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Manage_flightsLayout.setVerticalGroup(
            Manage_flightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_flightsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(card_home1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        internal_cardstack.add(Manage_flights, "Manage_flights");

        jLabel3.setText("Add flights");

        javax.swing.GroupLayout Add_flightLayout = new javax.swing.GroupLayout(Add_flight);
        Add_flight.setLayout(Add_flightLayout);
        Add_flightLayout.setHorizontalGroup(
            Add_flightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_flightLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(722, Short.MAX_VALUE))
        );
        Add_flightLayout.setVerticalGroup(
            Add_flightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_flightLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel3)
                .addContainerGap(920, Short.MAX_VALUE))
        );

        internal_cardstack.add(Add_flight, "Add_flight");
        Add_flight.getAccessibleContext().setAccessibleName("");

        jLabel4.setText("No fly list");

        javax.swing.GroupLayout View_NoFlyListLayout = new javax.swing.GroupLayout(View_NoFlyList);
        View_NoFlyList.setLayout(View_NoFlyListLayout);
        View_NoFlyListLayout.setHorizontalGroup(
            View_NoFlyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_NoFlyListLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(710, Short.MAX_VALUE))
        );
        View_NoFlyListLayout.setVerticalGroup(
            View_NoFlyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_NoFlyListLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel4)
                .addContainerGap(973, Short.MAX_VALUE))
        );

        internal_cardstack.add(View_NoFlyList, "View_NoFlyList");

        javax.swing.GroupLayout Landing_pageLayout = new javax.swing.GroupLayout(Landing_page);
        Landing_page.setLayout(Landing_pageLayout);
        Landing_pageLayout.setHorizontalGroup(
            Landing_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Landing_pageLayout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internal_cardstack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Landing_pageLayout.setVerticalGroup(
            Landing_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(internal_cardstack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Navbar.getAccessibleContext().setAccessibleName("Navbar");

        Top_cardstack.add(Landing_page, "Landing_page");
        Landing_page.getAccessibleContext().setAccessibleName("Landing_page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Top_cardstack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Top_cardstack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Top_cardstack.getAccessibleContext().setAccessibleName("Top_cardstack");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_fieldActionPerformed

    private void Password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_fieldActionPerformed

    private void Signin_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Signin_labelMouseClicked
        T_cardstack.show(this.Top_cardstack, "Landing_page");
    }//GEN-LAST:event_Signin_labelMouseClicked

    private void Home_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_labelMouseClicked

        this.Home_Highlight.setBackground(Color.BLACK);
        this.Manage_flight_highlight.setBackground(Color.WHITE);
        this.Add_flight_highlight.setBackground(Color.WHITE);
        this.NoFlyList_highlight.setBackground(Color.WHITE);
        inner_cardstack.show(this.internal_cardstack, "Home");
        
    }//GEN-LAST:event_Home_labelMouseClicked

    private void Manage_flight_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Manage_flight_labelMouseClicked

        this.Home_Highlight.setBackground(Color.WHITE);
        this.Manage_flight_highlight.setBackground(Color.BLACK);
        this.Add_flight_highlight.setBackground(Color.WHITE);
        this.NoFlyList_highlight.setBackground(Color.WHITE);
        inner_cardstack.show(this.internal_cardstack, "Manage_flights");
        
    }//GEN-LAST:event_Manage_flight_labelMouseClicked

    private void Add_flight_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_flight_labelMouseClicked

        this.Home_Highlight.setBackground(Color.WHITE);
        this.Manage_flight_highlight.setBackground(Color.WHITE);
        this.Add_flight_highlight.setBackground(Color.BLACK);
        this.NoFlyList_highlight.setBackground(Color.WHITE);
        inner_cardstack.show(this.internal_cardstack, "Add_flight");
        
    }//GEN-LAST:event_Add_flight_labelMouseClicked

    private void NoFlyList_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoFlyList_labelMouseClicked
 
        this.Home_Highlight.setBackground(Color.WHITE);
        this.Manage_flight_highlight.setBackground(Color.WHITE);
        this.Add_flight_highlight.setBackground(Color.WHITE);
        this.NoFlyList_highlight.setBackground(Color.BLACK);
        inner_cardstack.show(this.internal_cardstack, "View_NoFlyList");
        
    }//GEN-LAST:event_NoFlyList_labelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_flight;
    private javax.swing.JPanel Add_flight_highlight;
    private javax.swing.JLabel Add_flight_label;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Home_Highlight;
    private javax.swing.JLabel Home_label;
    private javax.swing.JPanel Image_panel;
    private javax.swing.JPanel Landing_page;
    private javax.swing.JPanel Login_page;
    private javax.swing.JPanel Manage_flight_highlight;
    private javax.swing.JLabel Manage_flight_label;
    private javax.swing.JPanel Manage_flights;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel NoFlyList_highlight;
    private javax.swing.JLabel NoFlyList_label;
    private javax.swing.JTextField Password_field;
    private javax.swing.JLabel Password_label;
    private javax.swing.JPanel Sigin_panel;
    private javax.swing.JLabel Signin_label;
    private javax.swing.JPanel Top_cardstack;
    private javax.swing.JTextField Username_field;
    private javax.swing.JLabel Username_label;
    private javax.swing.JPanel View_NoFlyList;
    private javax.swing.JLabel Welcome_label;
    private javax.swing.JPanel card_home;
    private javax.swing.JPanel card_home1;
    private javax.swing.JPanel home1;
    private javax.swing.JPanel home2;
    private javax.swing.JPanel home3;
    private javax.swing.JPanel home4;
    private javax.swing.JLabel image_label;
    private javax.swing.JPanel internal_cardstack;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCompanyinfo;
    private javax.swing.JLabel jLabelCompanyinfo1;
    private javax.swing.JLabel jLabeladdress;
    private javax.swing.JLabel jLabeldesignation;
    private javax.swing.JLabel jLabelfirstname;
    private javax.swing.JLabel jLabelhomelite;
    private javax.swing.JLabel jLabelhomelite1;
    private javax.swing.JLabel jLabellastname;
    private javax.swing.JLabel jLabelsalary;
    private javax.swing.JLabel lbl_AdminProfile;
    private javax.swing.JLabel lbl_AdminProfile1;
    // End of variables declaration//GEN-END:variables
}
