/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.ArrayList;
import java.util.HashSet;

public class Admin_GUI extends javax.swing.JFrame {
    private CardLayout T_cardstack;
    private CardLayout inner_cardstack;
    private ArrayList<JPanel> highlights;
    
    public Admin_GUI() {
        initComponents();
        setVisible(true);
        T_cardstack = (CardLayout) this.Top_cardstack.getLayout();
        inner_cardstack = (CardLayout) this.internal_cardstack.getLayout();
        
        highlights = new ArrayList<JPanel>();
        highlights.add(this.highlight_home);
        highlights.add(this.highlight_manageFlights);
        highlights.add(this.highlight_addFlight);
        highlights.add(this.highlight_noFlyList);
    }
    
    private void setHighlights(String btn_name){
       for(int i=0; i<highlights.size(); i++){
           JPanel hl = highlights.get(i);
           
           if(hl.getName() == btn_name)
                hl.setBackground(Color.decode("#FEB63E"));
           else
               hl.setBackground(Color.decode("#4D5061"));
       }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top_cardstack = new javax.swing.JPanel();
        Login_page = new javax.swing.JPanel();
        Sigin_panel = new javax.swing.JPanel();
        Welcome_label = new javax.swing.JLabel();
        Username_field = new javax.swing.JTextField();
        Username_label = new javax.swing.JLabel();
        Password_label = new javax.swing.JLabel();
        Signin_label = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        txtbox_password = new javax.swing.JPasswordField();
        Image_panel = new javax.swing.JPanel();
        image_label = new javax.swing.JLabel();
        Landing_page = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        highlight_home = new javax.swing.JPanel();
        highlight_manageFlights = new javax.swing.JPanel();
        highlight_addFlight = new javax.swing.JPanel();
        highlight_noFlyList = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        Home_label = new javax.swing.JLabel();
        btn_manageFlights = new javax.swing.JPanel();
        Manage_flight_label = new javax.swing.JLabel();
        btn_addFlight = new javax.swing.JPanel();
        Add_flight_label = new javax.swing.JLabel();
        btn_noFlyList = new javax.swing.JPanel();
        NoFlyList_label = new javax.swing.JLabel();
        internal_cardstack = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        panel_empInfoBackdrop = new javax.swing.JPanel();
        lbl_employeeInfo = new javax.swing.JLabel();
        panel_empInfo = new javax.swing.JPanel();
        lbl_firstName = new javax.swing.JLabel();
        txtbox_firstName = new javax.swing.JTextField();
        lbl_lastName = new javax.swing.JLabel();
        txtbox_lastName = new javax.swing.JTextField();
        lbl_CNIC = new javax.swing.JLabel();
        txtbox_CNIC = new javax.swing.JTextField();
        lbl_address = new javax.swing.JLabel();
        txtbox_address = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(2, 200), new java.awt.Dimension(32767, 200));
        lbl_designation = new javax.swing.JLabel();
        txtbox_designation = new javax.swing.JTextField();
        lbl_salary = new javax.swing.JLabel();
        txtbox_salary = new javax.swing.JTextField();
        Manage_flights = new javax.swing.JPanel();
        Header2 = new javax.swing.JPanel();
        Title2 = new javax.swing.JLabel();
        Seperator2 = new javax.swing.JLabel();
        Home_lite2 = new javax.swing.JLabel();
        Company_panel2 = new javax.swing.JPanel();
        Company_info_label2 = new javax.swing.JLabel();
        Info_panel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Add_flight = new javax.swing.JPanel();
        Header1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Seperator1 = new javax.swing.JLabel();
        Home_lite1 = new javax.swing.JLabel();
        Company_panel1 = new javax.swing.JPanel();
        Company_info_label1 = new javax.swing.JLabel();
        Info_panel2 = new javax.swing.JPanel();
        FirstName_label1 = new javax.swing.JLabel();
        LastName_label1 = new javax.swing.JLabel();
        CNIC_label1 = new javax.swing.JLabel();
        Designation_label1 = new javax.swing.JLabel();
        Address_label1 = new javax.swing.JLabel();
        Salary_label1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        View_NoFlyList = new javax.swing.JPanel();
        Header3 = new javax.swing.JPanel();
        Title3 = new javax.swing.JLabel();
        Seperator3 = new javax.swing.JLabel();
        Home_lite3 = new javax.swing.JLabel();
        Company_panel3 = new javax.swing.JPanel();
        Company_info_label3 = new javax.swing.JLabel();
        Info_panel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Top_cardstack.setLayout(new java.awt.CardLayout());

        Sigin_panel.setBackground(new java.awt.Color(254, 182, 62));

        Welcome_label.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        Welcome_label.setForeground(new java.awt.Color(255, 255, 255));
        Welcome_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome_label.setText("Welcome to XYZ Airways");

        Username_field.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        Username_field.setBorder(null);
        Username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_fieldActionPerformed(evt);
            }
        });

        Username_label.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        Username_label.setForeground(new java.awt.Color(255, 255, 255));
        Username_label.setText("Username");

        Password_label.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        Password_label.setForeground(new java.awt.Color(255, 255, 255));
        Password_label.setText("Password");

        Signin_label.setBackground(new java.awt.Color(77, 80, 97));
        Signin_label.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        Signin_label.setForeground(new java.awt.Color(255, 255, 255));
        Signin_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Signin_label.setText("Sign in");
        Signin_label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Signin_label.setOpaque(true);
        Signin_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Signin_labelMouseClicked(evt);
            }
        });

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/arrow-91-24.png"))); // NOI18N
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });

        txtbox_password.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txtbox_password.setBorder(null);

        javax.swing.GroupLayout Sigin_panelLayout = new javax.swing.GroupLayout(Sigin_panel);
        Sigin_panel.setLayout(Sigin_panelLayout);
        Sigin_panelLayout.setHorizontalGroup(
            Sigin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sigin_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sigin_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Signin_label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(Sigin_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Sigin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Welcome_label, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addGroup(Sigin_panelLayout.createSequentialGroup()
                        .addGroup(Sigin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Username_label)
                            .addComponent(Username_field)
                            .addComponent(txtbox_password, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Sigin_panelLayout.setVerticalGroup(
            Sigin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sigin_panelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(Welcome_label)
                .addGap(54, 54, 54)
                .addComponent(Username_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbox_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Signin_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addContainerGap())
        );

        Image_panel.setBackground(new java.awt.Color(255, 255, 255));

        image_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/Plane_image.jpg"))); // NOI18N

        javax.swing.GroupLayout Image_panelLayout = new javax.swing.GroupLayout(Image_panel);
        Image_panel.setLayout(Image_panelLayout);
        Image_panelLayout.setHorizontalGroup(
            Image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Image_panelLayout.setVerticalGroup(
            Image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Login_pageLayout = new javax.swing.GroupLayout(Login_page);
        Login_page.setLayout(Login_pageLayout);
        Login_pageLayout.setHorizontalGroup(
            Login_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_pageLayout.createSequentialGroup()
                .addComponent(Sigin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Image_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        Login_pageLayout.setVerticalGroup(
            Login_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Sigin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Image_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Top_cardstack.add(Login_page, "Login_card");
        Login_page.getAccessibleContext().setAccessibleName("Login_page");

        Landing_page.setPreferredSize(new java.awt.Dimension(612, 408));

        Navbar.setBackground(new java.awt.Color(48, 50, 61));

        highlight_home.setBackground(new java.awt.Color(254, 182, 62));
        highlight_home.setName("highlight_home"); // NOI18N

        javax.swing.GroupLayout highlight_homeLayout = new javax.swing.GroupLayout(highlight_home);
        highlight_home.setLayout(highlight_homeLayout);
        highlight_homeLayout.setHorizontalGroup(
            highlight_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        highlight_homeLayout.setVerticalGroup(
            highlight_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        highlight_manageFlights.setBackground(new java.awt.Color(77, 80, 97));
        highlight_manageFlights.setName("highlight_manageFlights"); // NOI18N

        javax.swing.GroupLayout highlight_manageFlightsLayout = new javax.swing.GroupLayout(highlight_manageFlights);
        highlight_manageFlights.setLayout(highlight_manageFlightsLayout);
        highlight_manageFlightsLayout.setHorizontalGroup(
            highlight_manageFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        highlight_manageFlightsLayout.setVerticalGroup(
            highlight_manageFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        highlight_addFlight.setBackground(new java.awt.Color(77, 80, 97));
        highlight_addFlight.setName("highlight_addFlight"); // NOI18N

        javax.swing.GroupLayout highlight_addFlightLayout = new javax.swing.GroupLayout(highlight_addFlight);
        highlight_addFlight.setLayout(highlight_addFlightLayout);
        highlight_addFlightLayout.setHorizontalGroup(
            highlight_addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        highlight_addFlightLayout.setVerticalGroup(
            highlight_addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        highlight_noFlyList.setBackground(new java.awt.Color(77, 80, 97));
        highlight_noFlyList.setName("highlight_noFlyList"); // NOI18N

        javax.swing.GroupLayout highlight_noFlyListLayout = new javax.swing.GroupLayout(highlight_noFlyList);
        highlight_noFlyList.setLayout(highlight_noFlyListLayout);
        highlight_noFlyListLayout.setHorizontalGroup(
            highlight_noFlyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        highlight_noFlyListLayout.setVerticalGroup(
            highlight_noFlyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_home.setBackground(new java.awt.Color(77, 80, 97));
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });

        Home_label.setBackground(new java.awt.Color(254, 182, 62));
        Home_label.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        Home_label.setForeground(new java.awt.Color(255, 255, 255));
        Home_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/home-2-16.png"))); // NOI18N
        Home_label.setText("HOME");
        Home_label.setIconTextGap(5);

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Home_label)
                .addContainerGap())
        );

        btn_manageFlights.setBackground(new java.awt.Color(77, 80, 97));
        btn_manageFlights.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_manageFlights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_manageFlightsMouseClicked(evt);
            }
        });

        Manage_flight_label.setBackground(new java.awt.Color(254, 182, 62));
        Manage_flight_label.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        Manage_flight_label.setForeground(new java.awt.Color(255, 255, 255));
        Manage_flight_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/airplane-5-16.png"))); // NOI18N
        Manage_flight_label.setText("MANAGE FLIGHTS");
        Manage_flight_label.setIconTextGap(5);

        javax.swing.GroupLayout btn_manageFlightsLayout = new javax.swing.GroupLayout(btn_manageFlights);
        btn_manageFlights.setLayout(btn_manageFlightsLayout);
        btn_manageFlightsLayout.setHorizontalGroup(
            btn_manageFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_manageFlightsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Manage_flight_label)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        btn_manageFlightsLayout.setVerticalGroup(
            btn_manageFlightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_manageFlightsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Manage_flight_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_addFlight.setBackground(new java.awt.Color(77, 80, 97));
        btn_addFlight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addFlightMouseClicked(evt);
            }
        });

        Add_flight_label.setBackground(new java.awt.Color(254, 182, 62));
        Add_flight_label.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        Add_flight_label.setForeground(new java.awt.Color(255, 255, 255));
        Add_flight_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/plus-4-16.png"))); // NOI18N
        Add_flight_label.setText("ADD FLIGHT");
        Add_flight_label.setIconTextGap(5);

        javax.swing.GroupLayout btn_addFlightLayout = new javax.swing.GroupLayout(btn_addFlight);
        btn_addFlight.setLayout(btn_addFlightLayout);
        btn_addFlightLayout.setHorizontalGroup(
            btn_addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Add_flight_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_addFlightLayout.setVerticalGroup(
            btn_addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Add_flight_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_noFlyList.setBackground(new java.awt.Color(77, 80, 97));
        btn_noFlyList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_noFlyList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_noFlyListMouseClicked(evt);
            }
        });

        NoFlyList_label.setBackground(new java.awt.Color(254, 182, 62));
        NoFlyList_label.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        NoFlyList_label.setForeground(new java.awt.Color(255, 255, 255));
        NoFlyList_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/remove-user-16.png"))); // NOI18N
        NoFlyList_label.setText("MANAGE NO-FLY LIST");
        NoFlyList_label.setIconTextGap(5);

        javax.swing.GroupLayout btn_noFlyListLayout = new javax.swing.GroupLayout(btn_noFlyList);
        btn_noFlyList.setLayout(btn_noFlyListLayout);
        btn_noFlyListLayout.setHorizontalGroup(
            btn_noFlyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_noFlyListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NoFlyList_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_noFlyListLayout.setVerticalGroup(
            btn_noFlyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_noFlyListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NoFlyList_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(highlight_manageFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highlight_addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highlight_noFlyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highlight_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_manageFlights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_addFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_noFlyList, javax.swing.GroupLayout.PREFERRED_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap())
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(highlight_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(highlight_manageFlights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_manageFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(highlight_addFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_addFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(highlight_noFlyList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_noFlyList, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        highlight_home.getAccessibleContext().setAccessibleName("highlight_home");
        highlight_manageFlights.getAccessibleContext().setAccessibleName("highlight_manageFlights");
        highlight_addFlight.getAccessibleContext().setAccessibleName("highlight_addFlight");
        highlight_noFlyList.getAccessibleContext().setAccessibleName("highlight_noFlyList");

        internal_cardstack.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(205, 209, 196));

        panel_empInfoBackdrop.setBackground(new java.awt.Color(254, 182, 62));

        lbl_employeeInfo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lbl_employeeInfo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_employeeInfo.setText("EMPLOYEE INFORMATION");

        javax.swing.GroupLayout panel_empInfoBackdropLayout = new javax.swing.GroupLayout(panel_empInfoBackdrop);
        panel_empInfoBackdrop.setLayout(panel_empInfoBackdropLayout);
        panel_empInfoBackdropLayout.setHorizontalGroup(
            panel_empInfoBackdropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_empInfoBackdropLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_employeeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_empInfoBackdropLayout.setVerticalGroup(
            panel_empInfoBackdropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_empInfoBackdropLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_employeeInfo)
                .addContainerGap())
        );

        panel_empInfo.setBackground(new java.awt.Color(205, 209, 196));
        panel_empInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 182, 62), 5, true));

        lbl_firstName.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        lbl_firstName.setForeground(new java.awt.Color(48, 50, 61));
        lbl_firstName.setText("First Name:");

        txtbox_firstName.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txtbox_firstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 182, 62), 2, true));
        txtbox_firstName.setOpaque(false);

        lbl_lastName.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        lbl_lastName.setForeground(new java.awt.Color(48, 50, 61));
        lbl_lastName.setText("Last Name:");

        txtbox_lastName.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txtbox_lastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 182, 62), 2, true));
        txtbox_lastName.setOpaque(false);

        lbl_CNIC.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        lbl_CNIC.setForeground(new java.awt.Color(48, 50, 61));
        lbl_CNIC.setText("CNIC:");

        txtbox_CNIC.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txtbox_CNIC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 182, 62), 2, true));
        txtbox_CNIC.setOpaque(false);

        lbl_address.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        lbl_address.setForeground(new java.awt.Color(48, 50, 61));
        lbl_address.setText("Address:");

        txtbox_address.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txtbox_address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 182, 62), 2, true));
        txtbox_address.setOpaque(false);

        filler1.setBackground(new java.awt.Color(254, 182, 62));
        filler1.setOpaque(true);

        lbl_designation.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        lbl_designation.setForeground(new java.awt.Color(48, 50, 61));
        lbl_designation.setText("Designation:");

        txtbox_designation.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txtbox_designation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 182, 62), 2, true));
        txtbox_designation.setFocusable(false);
        txtbox_designation.setOpaque(false);

        lbl_salary.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        lbl_salary.setForeground(new java.awt.Color(48, 50, 61));
        lbl_salary.setText("Salary:");

        txtbox_salary.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txtbox_salary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 182, 62), 2, true));
        txtbox_salary.setFocusable(false);
        txtbox_salary.setOpaque(false);

        javax.swing.GroupLayout panel_empInfoLayout = new javax.swing.GroupLayout(panel_empInfo);
        panel_empInfo.setLayout(panel_empInfoLayout);
        panel_empInfoLayout.setHorizontalGroup(
            panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_empInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_empInfoLayout.createSequentialGroup()
                        .addComponent(lbl_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbox_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_empInfoLayout.createSequentialGroup()
                        .addComponent(lbl_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbox_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_empInfoLayout.createSequentialGroup()
                        .addComponent(lbl_CNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbox_CNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_empInfoLayout.createSequentialGroup()
                        .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbox_address, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_empInfoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_designation, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbox_designation, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_empInfoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbox_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panel_empInfoLayout.setVerticalGroup(
            panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_empInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_empInfoLayout.createSequentialGroup()
                        .addGroup(panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_designation)
                            .addComponent(txtbox_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_salary)
                            .addComponent(txtbox_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_empInfoLayout.createSequentialGroup()
                        .addGroup(panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_firstName)
                            .addComponent(txtbox_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_lastName)
                            .addComponent(txtbox_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CNIC)
                            .addComponent(txtbox_CNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_empInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_address)
                            .addComponent(txtbox_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_empInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_empInfoBackdrop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_empInfoBackdrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_empInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        internal_cardstack.add(Home, "Home");

        Header2.setBackground(new java.awt.Color(255, 102, 102));
        Header2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Title2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Title2.setForeground(new java.awt.Color(51, 0, 51));
        Title2.setText(" Admin Profile ");
        Title2.setMaximumSize(new java.awt.Dimension(150, 30));

        Seperator2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Seperator2.setForeground(new java.awt.Color(102, 102, 102));
        Seperator2.setText("|");

        Home_lite2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        Home_lite2.setForeground(new java.awt.Color(102, 102, 102));
        Home_lite2.setText("Manage Flights");

        Company_panel2.setBackground(new java.awt.Color(255, 204, 102));

        Company_info_label2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        Company_info_label2.setForeground(new java.awt.Color(255, 255, 255));
        Company_info_label2.setText("Flight Information");

        javax.swing.GroupLayout Company_panel2Layout = new javax.swing.GroupLayout(Company_panel2);
        Company_panel2.setLayout(Company_panel2Layout);
        Company_panel2Layout.setHorizontalGroup(
            Company_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Company_panel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Company_info_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Company_panel2Layout.setVerticalGroup(
            Company_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Company_panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Company_info_label2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Info_panel1.setBackground(new java.awt.Color(250, 250, 250));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight ID", "Source", "Destination", "Capacity", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Time");
        }

        javax.swing.GroupLayout Info_panel1Layout = new javax.swing.GroupLayout(Info_panel1);
        Info_panel1.setLayout(Info_panel1Layout);
        Info_panel1Layout.setHorizontalGroup(
            Info_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Info_panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        Info_panel1Layout.setVerticalGroup(
            Info_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Info_panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(368, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Header2Layout = new javax.swing.GroupLayout(Header2);
        Header2.setLayout(Header2Layout);
        Header2Layout.setHorizontalGroup(
            Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header2Layout.createSequentialGroup()
                .addGroup(Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Info_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Header2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Seperator2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Home_lite2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Company_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 398, Short.MAX_VALUE))
        );
        Header2Layout.setVerticalGroup(
            Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seperator2)
                    .addComponent(Home_lite2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Company_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Info_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(671, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Manage_flightsLayout = new javax.swing.GroupLayout(Manage_flights);
        Manage_flights.setLayout(Manage_flightsLayout);
        Manage_flightsLayout.setHorizontalGroup(
            Manage_flightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_flightsLayout.createSequentialGroup()
                .addComponent(Header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Manage_flightsLayout.setVerticalGroup(
            Manage_flightsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Manage_flightsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        internal_cardstack.add(Manage_flights, "Manage_flights");

        Header1.setBackground(new java.awt.Color(255, 102, 102));
        Header1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Title1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(51, 0, 51));
        Title1.setText(" Admin Profile ");
        Title1.setMaximumSize(new java.awt.Dimension(150, 30));

        Seperator1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Seperator1.setForeground(new java.awt.Color(102, 102, 102));
        Seperator1.setText("|");

        Home_lite1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        Home_lite1.setForeground(new java.awt.Color(102, 102, 102));
        Home_lite1.setText("Add Flight");

        Company_panel1.setBackground(new java.awt.Color(255, 204, 102));

        Company_info_label1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        Company_info_label1.setForeground(new java.awt.Color(255, 255, 255));
        Company_info_label1.setText("Add New Flight");

        javax.swing.GroupLayout Company_panel1Layout = new javax.swing.GroupLayout(Company_panel1);
        Company_panel1.setLayout(Company_panel1Layout);
        Company_panel1Layout.setHorizontalGroup(
            Company_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Company_panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Company_info_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Company_panel1Layout.setVerticalGroup(
            Company_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Company_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Company_info_label1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Info_panel2.setBackground(new java.awt.Color(250, 250, 250));

        FirstName_label1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        FirstName_label1.setText("Flight ID:");

        LastName_label1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        LastName_label1.setText("Source:");

        CNIC_label1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        CNIC_label1.setText("Capacity:");

        Designation_label1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Designation_label1.setText("Destination:");

        Address_label1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Address_label1.setText("Time:");

        Salary_label1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        Salary_label1.setText("Cost:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Info_panel2Layout = new javax.swing.GroupLayout(Info_panel2);
        Info_panel2.setLayout(Info_panel2Layout);
        Info_panel2Layout.setHorizontalGroup(
            Info_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Info_panel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(Info_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Info_panel2Layout.createSequentialGroup()
                        .addComponent(FirstName_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Info_panel2Layout.createSequentialGroup()
                        .addGroup(Info_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Designation_label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(LastName_label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Info_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(157, 157, 157)
                .addGroup(Info_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Info_panel2Layout.createSequentialGroup()
                        .addComponent(Address_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Info_panel2Layout.createSequentialGroup()
                        .addComponent(CNIC_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Info_panel2Layout.createSequentialGroup()
                        .addComponent(Salary_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        Info_panel2Layout.setVerticalGroup(
            Info_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Info_panel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Info_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName_label1)
                    .addComponent(CNIC_label1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(Info_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName_label1)
                    .addComponent(Address_label1)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(Info_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salary_label1)
                    .addComponent(Designation_label1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(316, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Header1Layout = new javax.swing.GroupLayout(Header1);
        Header1.setLayout(Header1Layout);
        Header1Layout.setHorizontalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Info_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Header1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Seperator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Home_lite1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Company_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 398, Short.MAX_VALUE))
        );
        Header1Layout.setVerticalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seperator1)
                    .addComponent(Home_lite1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Company_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Info_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(671, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Add_flightLayout = new javax.swing.GroupLayout(Add_flight);
        Add_flight.setLayout(Add_flightLayout);
        Add_flightLayout.setHorizontalGroup(
            Add_flightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_flightLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Add_flightLayout.setVerticalGroup(
            Add_flightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_flightLayout.createSequentialGroup()
                .addComponent(Header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        internal_cardstack.add(Add_flight, "Add_flight");
        Add_flight.getAccessibleContext().setAccessibleName("");

        Header3.setBackground(new java.awt.Color(255, 102, 102));
        Header3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Title3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        Title3.setForeground(new java.awt.Color(51, 0, 51));
        Title3.setText(" Admin Profile ");
        Title3.setMaximumSize(new java.awt.Dimension(150, 30));

        Seperator3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Seperator3.setForeground(new java.awt.Color(102, 102, 102));
        Seperator3.setText("|");

        Home_lite3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        Home_lite3.setForeground(new java.awt.Color(102, 102, 102));
        Home_lite3.setText("No Fly List");

        Company_panel3.setBackground(new java.awt.Color(255, 204, 102));

        Company_info_label3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        Company_info_label3.setForeground(new java.awt.Color(255, 255, 255));
        Company_info_label3.setText("Customer No Fly List");

        javax.swing.GroupLayout Company_panel3Layout = new javax.swing.GroupLayout(Company_panel3);
        Company_panel3.setLayout(Company_panel3Layout);
        Company_panel3Layout.setHorizontalGroup(
            Company_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Company_panel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Company_info_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Company_panel3Layout.setVerticalGroup(
            Company_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Company_panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Company_info_label3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Info_panel3.setBackground(new java.awt.Color(250, 250, 250));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer CNIC", "First Name", "Last Name", "Contact Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Add New Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Info_panel3Layout = new javax.swing.GroupLayout(Info_panel3);
        Info_panel3.setLayout(Info_panel3Layout);
        Info_panel3Layout.setHorizontalGroup(
            Info_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Info_panel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Info_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        Info_panel3Layout.setVerticalGroup(
            Info_panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Info_panel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Header3Layout = new javax.swing.GroupLayout(Header3);
        Header3.setLayout(Header3Layout);
        Header3Layout.setHorizontalGroup(
            Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header3Layout.createSequentialGroup()
                .addGroup(Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Info_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Header3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Seperator3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Home_lite3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Company_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 203, Short.MAX_VALUE))
        );
        Header3Layout.setVerticalGroup(
            Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seperator3)
                    .addComponent(Home_lite3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Company_panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Info_panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout View_NoFlyListLayout = new javax.swing.GroupLayout(View_NoFlyList);
        View_NoFlyList.setLayout(View_NoFlyListLayout);
        View_NoFlyListLayout.setHorizontalGroup(
            View_NoFlyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_NoFlyListLayout.createSequentialGroup()
                .addComponent(Header3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        View_NoFlyListLayout.setVerticalGroup(
            View_NoFlyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, View_NoFlyListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Header3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        internal_cardstack.add(View_NoFlyList, "View_NoFlyList");

        javax.swing.GroupLayout Landing_pageLayout = new javax.swing.GroupLayout(Landing_page);
        Landing_page.setLayout(Landing_pageLayout);
        Landing_pageLayout.setHorizontalGroup(
            Landing_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Landing_pageLayout.createSequentialGroup()
                .addComponent(Navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(internal_cardstack, javax.swing.GroupLayout.PREFERRED_SIZE, 685, Short.MAX_VALUE))
        );
        Landing_pageLayout.setVerticalGroup(
            Landing_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internal_cardstack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 407, Short.MAX_VALUE)
            .addComponent(Navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Navbar.getAccessibleContext().setAccessibleName("Navbar");

        Top_cardstack.add(Landing_page, "Landing_page");
        Landing_page.getAccessibleContext().setAccessibleName("Landing_page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Top_cardstack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Top_cardstack, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Top_cardstack.getAccessibleContext().setAccessibleName("Top_cardstack");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_fieldActionPerformed

    private void Signin_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Signin_labelMouseClicked
        T_cardstack.show(this.Top_cardstack, "Landing_page");
    }//GEN-LAST:event_Signin_labelMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        this.dispose();
        JHome home = new JHome();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        this.inner_cardstack.show(this.internal_cardstack, "Home");
        this.setHighlights("highlight_home");
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_manageFlightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manageFlightsMouseClicked
        this.inner_cardstack.show(this.internal_cardstack, "Manage_flights");
        this.setHighlights("highlight_manageFlights");
    }//GEN-LAST:event_btn_manageFlightsMouseClicked

    private void btn_addFlightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addFlightMouseClicked
        this.inner_cardstack.show(this.internal_cardstack, "Add_flight");
        this.setHighlights("highlight_addFlight");
    }//GEN-LAST:event_btn_addFlightMouseClicked

    private void btn_noFlyListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_noFlyListMouseClicked
        this.inner_cardstack.show(this.internal_cardstack, "View_NoFlyList");
        this.setHighlights("highlight_noFlyList");
    }//GEN-LAST:event_btn_noFlyListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_flight;
    private javax.swing.JLabel Add_flight_label;
    private javax.swing.JLabel Address_label1;
    private javax.swing.JLabel CNIC_label1;
    private javax.swing.JLabel Company_info_label1;
    private javax.swing.JLabel Company_info_label2;
    private javax.swing.JLabel Company_info_label3;
    private javax.swing.JPanel Company_panel1;
    private javax.swing.JPanel Company_panel2;
    private javax.swing.JPanel Company_panel3;
    private javax.swing.JLabel Designation_label1;
    private javax.swing.JLabel FirstName_label1;
    private javax.swing.JPanel Header1;
    private javax.swing.JPanel Header2;
    private javax.swing.JPanel Header3;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel Home_label;
    private javax.swing.JLabel Home_lite1;
    private javax.swing.JLabel Home_lite2;
    private javax.swing.JLabel Home_lite3;
    private javax.swing.JPanel Image_panel;
    private javax.swing.JPanel Info_panel1;
    private javax.swing.JPanel Info_panel2;
    private javax.swing.JPanel Info_panel3;
    private javax.swing.JPanel Landing_page;
    private javax.swing.JLabel LastName_label1;
    private javax.swing.JPanel Login_page;
    private javax.swing.JLabel Manage_flight_label;
    private javax.swing.JPanel Manage_flights;
    private javax.swing.JPanel Navbar;
    private javax.swing.JLabel NoFlyList_label;
    private javax.swing.JLabel Password_label;
    private javax.swing.JLabel Salary_label1;
    private javax.swing.JLabel Seperator1;
    private javax.swing.JLabel Seperator2;
    private javax.swing.JLabel Seperator3;
    private javax.swing.JPanel Sigin_panel;
    private javax.swing.JLabel Signin_label;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JPanel Top_cardstack;
    private javax.swing.JTextField Username_field;
    private javax.swing.JLabel Username_label;
    private javax.swing.JPanel View_NoFlyList;
    private javax.swing.JLabel Welcome_label;
    private javax.swing.JPanel btn_addFlight;
    private javax.swing.JLabel btn_back;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_manageFlights;
    private javax.swing.JPanel btn_noFlyList;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel highlight_addFlight;
    private javax.swing.JPanel highlight_home;
    private javax.swing.JPanel highlight_manageFlights;
    private javax.swing.JPanel highlight_noFlyList;
    private javax.swing.JLabel image_label;
    private javax.swing.JPanel internal_cardstack;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lbl_CNIC;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_designation;
    private javax.swing.JLabel lbl_employeeInfo;
    private javax.swing.JLabel lbl_firstName;
    private javax.swing.JLabel lbl_lastName;
    private javax.swing.JLabel lbl_salary;
    private javax.swing.JPanel panel_empInfo;
    private javax.swing.JPanel panel_empInfoBackdrop;
    private javax.swing.JTextField txtbox_CNIC;
    private javax.swing.JTextField txtbox_address;
    private javax.swing.JTextField txtbox_designation;
    private javax.swing.JTextField txtbox_firstName;
    private javax.swing.JTextField txtbox_lastName;
    private javax.swing.JPasswordField txtbox_password;
    private javax.swing.JTextField txtbox_salary;
    // End of variables declaration//GEN-END:variables
}
